### ISSUE TITLE
SNSをコメントアウトしたところ、グローバルナビの挙動がおかしい？

### ISSUE THREAD

**Issue by zzzzzz21** [zzzzzz21/vitabon.co.jp#1]
@kobaatsu 
Twitter、Facebookの部分をコメントアウトしたら、グローバルナビのアンカーリンクが意図した位置に動かなくなっている可能性があります。

原因を調べて対応策を施していただけませんでしょうか。

**Comment by kobaatsu** [comment]
アンカーはJSで制御しているので、そこを削除しました。
https://github.com/alvarotrigo/fullPage.js#options

こちらでご確認できます。
http://vitabon.okmijn.xyz/
